const CHATS = 'CHATS';
const LOADING = 'LOADING';
const COLLECTION = 'COLLECTION';
const TEMPERATURE = 'TEMPERATURE';
const CURRENT_CHAT = 'CURRENT_CHAT';
const USER_CREDENTIALS = 'USER_CREDENTIALS';

export { 
  CHATS, 
  LOADING,
  COLLECTION,
  TEMPERATURE,
  CURRENT_CHAT, 
  USER_CREDENTIALS 
};
