const SESSION = 'SESSION';
const TEMPERATURE = 'TEMPERATURE';
const CURRENT_CHAT = 'CURRENT_CHAT';
const USER_CREDENTIALS = 'USER_CREDENTIALS';

export { 
  SESSION, 
  TEMPERATURE,
  CURRENT_CHAT, 
  USER_CREDENTIALS 
};
